services:
  session_bot:
    build: .
    container_name: session_bot
    restart: unless-stopped
    environment:
      - ROOT_DIR=/app
      - HOST_IP=${HOST_IP}
      - CLIENT_NAME=${CLIENT_NAME:-default_client}
    volumes:
      - ./data:/app/data
      - ./plugins:/app/plugins
    ports:
      - "8089:8089"
#    user: "1000:1000"
#    extra_hosts:
#      - "sanroque:host-gateway"
#    extra_hosts:
#      - "hostmachine:${HOST_IP}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
