name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ts-test:
    name: TypeScript tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "export PATH=\"$HOME/.bun/bin:$PATH\"" >> $GITHUB_ENV
      - name: Install dependencies
        run: bun install
      - name: Run TS tests
        run: bun test

  py-test:
    name: Python tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run Python tests
        run: |
          . venv/bin/activate
          pytest -q